language: go
go:
  - 1.8.3
sudo: required
services:
  - docker

install: true

script:
  - ./build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push xphyr/k8s_isi_provisioner;
    fi
