kind: Pod
apiVersion: v1
metadata:
  name: isilon-provisioner
spec:
  containers:
    - name: isilon-provisioner
      image: isilon-provisioner:latest
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: pv-volume
          mountPath: /tmp/isilon-provisioner
  volumes:
    - name: pv-volume
      isilon:
        path: /tmp/isilon-provisioner
